### ISSUE TITLE
Allow For control of Multiple Hosts

### ISSUE THREAD

**Issue by Makr91** [pikvm/pikvm#1]
Hello

I am s till in the process of getting this to work on my ZeroW's and Pi 3 as that is what the Fmstrat/diy-ipmi used when I first set up the system. I wanted to switch to this to see if there is a way that we could open this up to manage multiple hosts at a time from a RPi4 or if it would be better to manage this on a Per Host Basis with 3 seperate ZeroW's?

**Comment by mdevaev** [comment]
One RPi must manage one host, this is the basis of the system architecture. There are several reasons for this:
  * The main way to get video we consider HDMI-CSI2 bridge. Only one video capture device can be connected because RPi has only one CSI2 socket.
  * RPI has only one OTG port and you will not be able to emulate several keyboards, mouse and disks.
  * The resources of the RPi will be enough to encode only one video stream with good FPS.
  * Etc.

If you need three maximally cheap KVM you should use three Zero.

Theoretically, if the software allowed multiple video capture devices to be used and multiple motherboards to be loaded, you would need RPi4, multiple Arduino boards to emulate the keyboard, and multiple HDMI-USB video capture devices. The situation is such that the final cost of such a solution will be approximately equal to the cost of buying three rpi4 boards and three HDMI-CSI2 bridges.

Diy-hdmi uses a very cheap image capture device that we support too, but let's be honest, it's really impossible to use for anything other than a text BIOS and an 80x24 terminal.
