### ISSUE TITLE
When you turn the audio control slider up from 0% or back to 0%, the screen goes black for few seconds

### ISSUE THREAD

**Issue by plia7** [pikvm/pikvm#1051]
**Describe the bug**
When you turn the audio control slider up from 0% or back to 0%, the screen goes black for few seconds.

**To Reproduce**
1. turn the audio control slider up from 0% or back to 0%.

**Expected behavior**
Screen doesn't turn black for few seconds.

**Screenshots**

**Desktop (please complete the following information):**
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4]
  - PiKVM platform [e.g. v2-hdmi]
  - Video capture type [e.g. CSI bridge]
  - KVMD version: `pacman -Q | grep kvmd`
  3.232-1
  - uStreamer version: `pacman -Q | grep ustreamer`
  - Linux kernel: `uname -a`

**Additional context**
For reference, in 3.169 it wasn't doing that.

**Comment by mdevaev** [comment]
It's not a bug, it's a feature. When changing from 0 to any other value, the stream requests an audio track. When changing to 0, the connection is terminated and a stream without sound is requested. This way we save traffic. A side effect of this is the blinking of the screen, this is not implemented in any other way.

Streaming without sound works with less delay because it does not require synchronization of the video stream with audio (and audio requires a small sound buffer). I can't do it any other way yet, but later I will transmit video and audio in separate streams.
