### ISSUE TITLE
Have Windows maximize by default

### ISSUE THREAD

**Issue by dsatcom** [pikvm/pikvm#1341]
**Is your feature request related to a problem? Please describe.**
Every time I load the pikvm I have to maximize the window and anytime the page refreshes I have to maximize the window again. While it only takes a second, I have many pikvms and I open them all in different tabs and it’s a pain to have to go into each one and maximize every day or every time the page refreshes

**Describe the solution you'd like**
Default the window to maximized or add a setting to set the window to automatically be maximized or not. 

**Describe alternatives you've considered**
another alternative would be a GET parameter like ?fullscreen=true or something to bookmark.

**Additional context**
I think if you surveyed most users, they probably all maximize the browser window and rarely use the unmaximized version

**Comment by mdevaev** [comment]
I've researched it a bit. Unfortunately, this feature cannot be implemented because the browser prohibits doing full-screen mode without user interaction (clicking somewhere, for example).

I made a slightly alternative mode: maximizing the entire tab. It does not solve the problem with key interception and may not be what you want at all, but I can't do anything better in modern browsers. Sorry.

Max-tab will be available in the next release:
![image](https://github.com/user-attachments/assets/996bc235-669c-49be-8876-cae2535b3af3)
