### ISSUE TITLE
Black and white option

### ISSUE THREAD

**Issue by sharicov** [pikvm/pikvm#186]
Could you please add black and white option for better image compression?
Thanks in advance

**Comment by mdevaev** [comment]
I'm working on H.264 compression, which will be much better than a black and white image. I won't be doing this right now, but I'll leave this iss for the future, as it's useful.

**Comment by mdevaev** [comment]
Since [H.264](https://github.com/pikvm/pikvm/blob/master/pages/webrtc.md) is now available and testing shows a significant reduction in traffic consumption, I don't think that the black-and-white image option is still relevant. The ancient KVMs used it because they did not have differential encoding, but now we have. In addition, to get a black-and-white image from RGB, processing on the CPU is required, since hardware conversion is not available for most encoding methods. So I'm closing it as unnecessary, unless something changes completely in the future.
