### ISSUE TITLE
Add ability to mount writable images

### ISSUE THREAD

**Issue by mallendeo** [pikvm/pikvm#21]
It would be really nice if we could mount read/write images to use them as virtual hdds or usb drives.

e.g: could be "writable" or "read-only"

![pikvm-usb-mock](https://user-images.githubusercontent.com/1578018/85956300-1d1bb280-b953-11ea-8c17-6d2472d334c4.png)

![pikvm-usb-mock](https://user-images.githubusercontent.com/1578018/85957036-e4320c80-b957-11ea-99ef-eb5b58c8a345.png)

**Comment by mdevaev** [comment]
To be honest this feature is already implemented but required some CLI actions to use. The reason is RO-filesystem. We have a separate partition on SD card to storing images. When user uploading the new image this partition comes to RW-mode, then switches back to RO. RO is necessary to pevent filesystem damage on power loss.

If we want to place the switch directly in the interface, the file system will have to be switched to write mode for a long time. Firstly, this will require a significant rework of the logic of work, and secondly, a frivolous user may just forget to switch everything back. So at the moment, I left only the possibility of using read-only images in the interface, because this is (among other things) the most frequent case, and images for writing can be connected via the console. In particular, there is a web terminal for this purpose. If you're interested in how this works, you can look at the `kvmd-otgmsd` command. I'll probably do what you ask in the future, but it's really a lot of work.

As for the interface, I really like the way it looks. I think I'll borrow an idea about the media type switch. The only thing is, I can't emulate HDD. This is limited by the current core capabilities. So for now, either CD-ROM or USB Flash.

**Comment by mallendeo** [comment]
Thank you. I didn't know about the `kvmd-otgmsd` command. It seems to work, but it doesn't show up on the UI

`rw && kvmd-otgmsd --set-image /var/lib/kvmd/msd/images/unraid-usb-small.img --set-rw 1 --set-cdrom 0`
![image](https://user-images.githubusercontent.com/1578018/86046316-06409300-ba1b-11ea-8cbe-cdfc11320a8b.png)

The `kvmd-otgmsd -m` (`kvmd-otgmsd -m | grep unraid`) command doesn't show the info of the current msd though. I think I can get around that for now.

**Comment by mdevaev** [comment]
Please show the output of `journalctl -u kvmd` during this error.

**Comment by mdevaev** [comment]
Okay, I think I reproduced the problem. "Offline" reports when you're disconnect drive. The log in that moment:
```
Jun 30 04:47:36 pikvm kvmd[328]: Traceback (most recent call last):
Jun 30 04:47:36 pikvm kvmd[328]:   File "/usr/lib/python3.8/site-packages/kvmd/plugins/msd/otg/__init__.py", line 437, in __reload_state
Jun 30 04:47:36 pikvm kvmd[328]:     raise MsdError("MSD has been switched to RW-mode manually")
Jun 30 04:47:36 pikvm kvmd[328]: kvmd.plugins.msd.MsdError: MSD has been switched to RW-mode manually
```
The reason is that the KVMD is quite paranoid in terms of tracking drive state. If you'he made some changes that do not cover its internal logic (for example, RW-mode), the system believes that it is better to stop working than to do something incomprehensible with possible disastrous consequences. Just switch the drive to RO mode and the interface will work again: `kvmd-otgmsd --set-rw=0`.

You should also know that the `rw`  ommand does not switch the partition to `/var/lib/kvmd`. It only applies to the basic functions of the operating system. For remounting use command `kvmd-helper-otgmsd-remount`. In addition, another useful command: `kvmd-helper-otgmsd-unlock`. It unlocks usb driver if the server's OS acquired it.

**Comment by mallendeo** [comment]
Just checked and it is the same error I'm getting. I was running `mount -o remount,rw /dev/mmcblk0p3` at boot, so that might be the case. Nice to know about those commands, thanks.

**Comment by connected201** [comment]
> 
> 
> Just checked and it is the same error I'm getting. I was running `mount -o remount,rw /dev/mmcblk0p3` at boot, so that might be the case. Nice to know about those commands, thanks.

Hi, you have solution about your use case?
best regards.

**Comment by mdevaev** [comment]
Note just for me: https://www.spinics.net/lists/linux-usb/msg214103.html

**Comment by connected201** [comment]
i tested and working very well, also i able to install linux on mounted .img file :)

**Comment by mdevaev** [comment]
It's time.

**Comment by mdevaev** [comment]
It's done and available since KVMD 3.126. Now you can upload the flash drive image to MSD, write some files to it or even install entire OS to the PiKVM MSD drive (I don't know why, but you can), and download the image back. Use the new feature wisely.

![image](https://user-images.githubusercontent.com/416259/180655834-41d53847-f4ae-4d4f-96af-42a7d24e9817.png)

**Comment by connected201** [comment]
Great improvement.

**Comment by sharicov** [comment]
Doesn't work for me, when connecting the image writable switches to Off automatically, only cli commands work:

kvmd-helper-otgmsd-remount rw
kvmd-otgmsd -i 0 --set-rw=1 --set-cdrom=0 --set-image=/var/lib/kvmd/msd/ventoy.img

**Comment by mdevaev** [comment]
Switch type to flash firstly, then RW flag (in gui both).

**Comment by sharicov** [comment]
That's exactly the order I'm doing it, rw switch to ro by itself when pressing connect.
BTW using the latest v2 version on zero 2 w

**Comment by mdevaev** [comment]
Maybe something wrong with permissions. Try new image on another sd card.

**Comment by sharicov** [comment]
Is there anything I can check in logs? I only installed fresh new system several days ago.

File permissions:
-rw-r--r-- 1 root root 19G Mar 29 04:58 ventoy.img

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by sharicov** [comment]
BTW in the guides (https://docs.pikvm.org/msd/#multiple-drives and others) it says PiKVM should be restarted when switching mass storage type, or ro to rw, in order host PC to recognize the change, it's not a must, running USB Tree Viewer as admin and restarting the PiKVM device does the same on USB level.

**Comment by mdevaev** [comment]
It depends on the host OS.

**Comment by sharicov** [comment]
Sure, talking about Windows
