### ISSUE TITLE
Quality of Life improvements to update / restart pikvm

### ISSUE THREAD

**Issue by tryallthethings** [pikvm/pikvm#47]
nice to have; low priority

- System and / or pikvm component update through web interface
- pikvm restart (system and / or daemon) via web interface
- update alias (.bashrc) or bash script similar to /usr/local/bin/rw to install the latest updates via pacman

**Comment by mdevaev** [comment]
> pikvm restart (system and / or daemon) via web interface

Why is this necessary?

**Comment by tryallthethings** [comment]
For example if an update requires a restart or in case of any issues.

**Comment by n1nj4888** [comment]
I have a hardware HDMI kvm switch which, when the switch port is changed to another host, pikvm does not show any video (No Signal) - In this case, if I then reboot the pikvm then shows the video fine... So at least in this scenario, having the option to reboot pikvm itself via the web gui would  be better rather than then having to log in to SSH to reboot every time I switch hosts. 

Obviously though, having a fix that correctly updated displayed the new host video on host switch would be preferred👍

**Comment by mdevaev** [comment]
@n1nj4888 You don't have to use a reboot to do this. Try simply reloading the HDMI EDID data: `/usr/bin/v4l2-ctl --device=/dev/kvmd-video --set-edid=file=/etc/kvmd/tc358743-edid.hex --fix-edid-checksums`

**Comment by ndastur** [comment]
Is this what "Reset Stream" does? If not could it be added?

**Comment by mdevaev** [comment]
Okay, what are we have today:
* Updating the OS is a complex operation that must be performed consciously, so it will not be done with one button as long as we use generic Linux OS and not something embedded like OpenWRT, or do not have a simple option to roll back all changes. For the same reason, I don't like the idea of command shortcuts: after the update, you need to do a reboot or an explicit ro.
* You can use [cmd gpio](https://docs.pikvm.org/gpio/#cmd) to pin command buttons like `reboot` and `poweroff`. Don't use it for update. So this is implemented already I think.
