### ISSUE TITLE
Wondering if Auvidea B102 will work with the Pi Zero W V2 image?

### ISSUE THREAD

**Issue by chilman408** [pikvm/pikvm#492]
Hello,

I'm wondering if the Auvidea B102 device is compatible with the Pi0W v2 Image?  

Like to go with this one as Mouser is an approved vendor for work.

**Comment by mdevaev** [comment]
I'm not sure that it will work and you won't be able to use it because auvidea uses non-standard ftal cables. The usual cable from the camera will not work. The one that comes in the kit will not fit the width to Zero.

I assume you want to use 60Hz otherwise I do not know why you need B102. The problem is that in CSI on Raspberry, the required number of data lines is not divorced for this to work. In this case I advise you to buy a Chinese device for Zero. There is no point in buying a B102.
