### ISSUE TITLE
PiKVM Hat v3 Oled screen issue

### ISSUE THREAD

**Issue by kitzler-walli** [pikvm/pikvm#554]
I just received my PiKVM hat v3 by mail and after assembling everthing seems to work just fine except for the oled screen. Do I have to enable it?
I used the os image provided specifically for this hardware so I thought that should work out of the box.

**Comment by mdevaev** [comment]
Hello. The OLED must be turned on after manual assembly, just like the fan controller. Pay attention to point 5 in the user manual: 
![image](https://user-images.githubusercontent.com/416259/144688138-6f06924f-c570-44fc-93e0-ec948980aece.png)

For support questions, you should contact [Discord](https://discord.gg/bpmXfz5) chat, not Github. There you will get an answer much faster from our specialists, and here you will have to wait until I wake up, because for sure we live in different time zones :)

**Comment by kitzler-walli** [comment]
Thank you for your support.
