### ISSUE TITLE
About remote USB mapping

### ISSUE THREAD

**Issue by wilinz** [pikvm/pikvm#702]
Is it possible to remotely map USB by installing programs on the remote OS

**Comment by weili71** [comment]
Thus, the USB device on the remote computer is mapped to the local machine controlled by IP KVM

**Comment by weili71** [comment]
> What do you mean?

Just like VMware, when USB is inserted, VMware will ask whether to map the USB device to the virtual machine, so that the USB device can be accessed in the virtual machine. Now the computer controlled by ipkvm is equivalent to virtual machine, and the remote computer is equivalent to physical machine. Now we hope to map the USB device on the remote computer to the computer controlled by ipkvm

**Comment by weili71** [comment]
> > What do you mean?
> 
> Just like VMware, when USB is inserted, VMware will ask whether to map the USB device to the virtual machine, so that the USB device can be accessed in the virtual machine. Now the computer controlled by ipkvm is equivalent to virtual machine, and the remote computer is equivalent to physical machine. Now we hope to map the USB device on the remote computer to the computer controlled by ipkvm

Can you see what I mean now？

**Comment by mdevaev** [comment]
PiKVM USB emulation uses the regular OS driver so if you want to map into something special you can use the OS settings for this.

**Comment by stevenruidigao** [comment]
I think what wilinz means is basically what I'm suggesting in #672.

**Comment by mdevaev** [comment]
Yes, I think so.
