### ISSUE TITLE
Is it possible to add audio support for USB HDMI dongle? (pikvm v2)

### ISSUE THREAD

**Issue by spcharc** [pikvm/pikvm#835]
I have noticed that the MS2109 based cheap USB dongles have an audio interface. This shows `hw:0` is the audio input device.
```
[kvmd-webterm@pikvm ~]$ cat /proc/asound/cards
 0 [MS2109         ]: USB-Audio - MS2109
                      MacroSilicon MS2109 at usb-0000:01:00.0-1.4, high speed
```
I have also noticed that pikvm has audio support on pikvm v3. For example this is from the pikvm v3 readme:
```
audio: {
    device = "hw:0,0"
    ...
}
```
I understand that only H264 stream supports video and audio at the same time, and that mjpeg stream is video only.
But I am wondering, is it possible for pikvm to stream mjpeg and audio as two separate streams, and let the browser to play both of them at the same time? I think modern browsers support playing two streams simultaneously?

**Comment by mdevaev** [comment]
Hello. I believe that this is possible in principle, but for this you will have to redo the entire browser code to work with videos.

The v2 documentation described that usb dongle is not a recommended hardware (and even described the reasons). This also means that all new features will be added primarily for CSI, because I don't have the resources to support this USB dongle black box and specialized solutions for it.

However, as usual, I'm open to accepting patches (if they don't break the existing logic and don't spoil the architecture of the system).
