### ISSUE TITLE
RFE: Add adjustable delay between characters when pasting text

### ISSUE THREAD

**Issue by rcpao** [pikvm/pikvm#858]
I am losing characters pasted into iOS devices.
Specifically, the Discord app's login and password fields.

**Comment by mdevaev** [comment]
Added slow typing mode. It will be available in the next release (in hour). This is a simple but not the best solution with the addition of a small delay, and it does not guarantee getting rid of the problems completely, because I would have to completely redo all HID plugins to implement a queue with trottling. But anyway it will work in almost all cases.
