### ISSUE TITLE
pikvm not working in bromite browser

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#887]
hi, i using on android devices bromite browser:  https://github.com/bromite/bromite
but pikvm not working on this browser :(
**bromite browser:**
![image](https://user-images.githubusercontent.com/20506433/204863097-851760cf-9fde-46f8-8fe0-6d50c0b33151.png)
**chrome browser:**
![image](https://user-images.githubusercontent.com/20506433/204863184-22c041ce-143b-4c3a-89b7-522a08fbbd13.png)

**Comment by mdevaev** [comment]
I see that a lot of things are disabled in this browser. I don't have Android on hand to debug this. Most likely the reason is that they broke something from the JS side. If you can get debugging output from the browser's JS console, I'll take a look at it and MAYBE be able to fix it: https://developer.chrome.com/docs/devtools/

**Comment by mdevaev** [comment]
Sup?

**Comment by connected201** [comment]
hi, mobile version don't have devtools like in desktop version, maybe i need to connect over ADB on android, i will try in a few days to solve.

**Comment by connected201** [comment]
strange things, today i opened pikvm in bromite and all work well. topic closed.
